### ISSUE TITLE
Facebook mediation adds READ_PHONE_STATE

### ISSUE THREAD

**Issue by bishiboosh** [appnexus/mobile-sdk-android#21]
When using the following dependency `compile 'com.appnexus.opensdk.mediatedviews:appnexus-facebook-mediation:[2,3)'`, READ_PHONE_STATE is added to the final `AndroidManifest.xml`

According to the manifest merger log, the reason is the following :

> android:uses-permission#android.permission.READ_PHONE_STATE
> IMPLIED from /home/valentin/Dev/android-studio-ws/android-allocine/Allocine/src/allocine/AndroidManifest.xml:2:1-129:12 reason: com.appnexus.opensdk.mediatedviews.Facebook has a targetSdkVersion < 4
> android:uses-permission#android.permission.READ_EXTERNAL_STORAGE

**Comment by bishiboosh** [comment]
Actually, this seems to be a bigger issue, if I remove the line from my build, I still have :

> android:uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
IMPLIED from /home/valentin/Dev/android-studio-ws/android-webediacore/testing/src/main/AndroidManifest.xml:2:1-70:12 reason: com.appnexus.opensdk has a targetSdkVersion < 4
android:uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from /home/valentin/Dev/android-studio-ws/android-webediacore/testing/src/main/AndroidManifest.xml:2:1-70:12 reason: com.appnexus.opensdk has a targetSdkVersion < 4

**Comment by anwzhang** [comment]
I have researched on this issue based on your merger log. It appears from the merger log that our SDK has a targetSdkVersion which is lower than 4, however, based on the gradle setup, our SDK is targeting minimal version 9: https://github.com/appnexus/mobile-sdk-android/blob/master/sdk/build.gradle

The pom file didn't show anything that's changing the build target.

I will spend more time debugging which part actually went wrong. In the mean time, can you tell me how urgent this is to your app development so that our team can prioritize the fix when we identify the root cause?

**Comment by josecu** [comment]
Hi Valentin,
Could you provide the Gradle version that you're using to compile your app?

Best,
Jose
