### ISSUE TITLE
Release numbering

### ISSUE THREAD

**Issue by erikgeurts** [appnexus/mobile-sdk-android#25]
When I see a release like https://github.com/appnexus/mobile-sdk-android/releases/tag/RC2.15.1 I wonder about the RC part. Does this mean Release Candidate?

The reason I'm asking is that I want to know which releases are considered to be 'stable' and which ones are just release candidates that should be used with extra care.

**Comment by josecu** [comment]
Hi Eric,
All the RC2.x releases are considered to be stable. The versioning system has not changed since the SDK was first released, at which point the "release candidate" designation was accurate. In the future, we may remove the "RC" in our version numbers to make it clear that the releases are stable, but apologies for any confusion caused by this designation in the meantime.

Best,
Jose

**Comment by erikgeurts** [comment]
Hi Jose,
Thanks for explaining. I'd like to propose to remove that RC designation rather sooner than later, because it confuses app developers who plan on using your SDKs and then get concerned to see that there are just RCs and alpha releases available.
Regards, Erik
