### ISSUE TITLE
NullPointerException on MediatedAdViewController#onAdFailed

### ISSUE THREAD

**Issue by SylvainGourdaut** [appnexus/mobile-sdk-android#34]
I experienced a crash using your SDK (v 4.2)
``
java.lang.NullPointerException: Attempt to invoke interface method 'void com.appnexus.opensdk.ut.UTAdRequester.continueWaterfall(com.appnexus.opensdk.ResultCode)' on a null object reference
                                                                           at com.appnexus.opensdk.MediatedAdViewController.onAdFailed(MediatedAdViewController.java:269)
``

The problematic code : 
``
        UTAdRequester requester = this.caller_requester.get();
        requester.continueWaterfall(reason);
``

As the UTAdRequester used (caller_requester) is a WeakReference, you should check the result of the get() before to use it.

FYI, it was introduced in V4.0.

**Comment by Kowshickkarthick** [comment]
HI @SylvainGourdaut,

Thanks for reaching out! 
This issue has been fixed in v4.3

Going forward, please submit SDK issues through our support portal at support.appnexus.com. By submitting through our portal, we can investigate and track the issue more efficiently. Please let me know if you have questions! We do not accept GitHub issues.
